import Bio
from Bio.Blast import NCBIWWW
from Bio.Blast import NCBIXML
from Bio.Seq import Seq

print(Bio.__version__)

# TENTEI EXECUTAR O COMANDO DE PESQUISA "NCBIWWW" MAS DEMORA MUITO PARA RETORNAR RESULTADO.
'''nicotiana_tabacum = "TGGGCCTCATATTTATCCTATATACCATGTTCGTATGGTGGCGCGATGTTCTACGTGAATCCACGTTCGAAGGACATCATACCAAAGTCGTACAATTAGGACCTCGATATGGTTTTATTCTGTTTATCGTATCGGAGGTTATGTTCTTTTTTGCTCTTTTTCGGGCTTCTTCTCATTCTTCTTTGGCACCTACGGTAGAG"
result_handle = NCBIWWW.qblast("blastn", "nt", nicotiana_tabacum)
blast_record = NCBIXML.read(result_handle)
print(blast_record)'''

print(f"\n1 - Reversing complement DNA 5' - 3' sequence:")
my_dna = Seq("GCATCGAGTGCATCGATGCTAGCATCGATGCAGTCATGACTGTACGTGACTGAC")
print(my_dna)
my_dna = Seq("GCATCGAGTGCATCGATGCTAGCATCGATGCAGTCATGACTGTACGTGACTGAC").reverse_complement()
print(my_dna)

print(f"\n2.1 - Making DNA 3' - 5' complement to make RNA sequence:")
my_dna_complement = Seq("TGGGCCTCATATTTATCCTATATACCATGTTCGTATGGTGGCGCGATGTTCTACGTGAATCCACGTTCGAAGGACATCATACCAAAGTCGTACAATTAGGACCTCGATATGGTTTTATTCTGTTTATCGTATCGGAGGTTATGTTCTTTTTTGCTCTTTTTCGGGCTTCTTCTCATTCTTCTTTGGCACCTACGGTAGAG")
print(my_dna_complement)
my_dna_complement = Seq("TGGGCCTCATATTTATCCTATATACCATGTTCGTATGGTGGCGCGATGTTCTACGTGAATCCACGTTCGAAGGACATCATACCAAAGTCGTACAATTAGGACCTCGATATGGTTTTATTCTGTTTATCGTATCGGAGGTTATGTTCTTTTTTGCTCTTTTTCGGGCTTCTTCTCATTCTTCTTTGGCACCTACGGTAGAG").complement()
print(my_dna_complement)

print("2.2 - Transcribing RNA sequence from DNA complement:")
rna_transcribed = my_dna_complement.complement_rna()
print(rna_transcribed)
print("2.3 - Translating RNA sequence to protein:")
my_protein = rna_transcribed.translate()
print(my_protein)
